spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/D:/database/H2database/soundCode
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create

  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false